version: '3.9'
services:

  ibmmq:
    image: ibm-messaging/mq
    container_name: ibm-mq
    build:
      context: ./mq
    ports:
      - "14140:1414"
      - "9443:9443"
      - "9157:9157"
    environment:
      LICENSE: "accept"
      MQ_QMGR_NAME: "QM1"
    #    volumes:
    #      - ~/mqm-data:/var/mqm
    platform: linux/amd64
    restart: unless-stopped
